spring:
  application:
    name: dls-maths
  profiles:
    active: mysql-local
server:
  address: 0.0.0.0
  port: 8070
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: secretpass
    key-store-type: PKCS12
    key-alias: springboot